### ISSUE TITLE
Activation code doesn't work

### ISSUE THREAD

**Issue by d4mation** [realbigplugins/psp-edd#8]
Noticed that despite showing up as being purchased through EDD Slack a few times that I don't think I had seen a license become activated yet.

Decided to quickly investigate and it is due to the code not matching up with the name of the Download on RBP.

https://github.com/realbigplugins/psp-edd/blob/master/psp-edd.php#L93

~~It should instead read:~~

~~`$license = new EDD_License( __FILE__, 'Project Panorama - Easy Digital Downloads', PSP_EDD_VER, 'Kyle Maurer' );`~~

~~We had this same problem over with EDD Slack as I was originally using the Plugin Name (As you are here), but over on EDD's site the Download was named simply "Slack".~~

~~https://github.com/realbigplugins/edd-slack/commit/674668c5b388a6e03a44aafebbaf7ac087ea5333~~

**Comment by d4mation** [comment]
Actually, I'm not quite right above. Since this plugin is hosted on RBP, you cannot use the simple `EDD_License` class as that points to EDD's site. If it were hosted there, the fix above would work.

Instead you should be using the `EDD_SL_Plugin_Updater` class which is a bit more involved unfortunately. LearnDash Gradebook or LearnDash Slack would be good examples to look at for getting Licensing implemented correctly to work with RBP.

**Comment by d4mation** [comment]
Checked into this a tad bit more after the customer who prompted my making this Issue opened a ticket on HelpScout (Not about being unable to activate the license though)

It seems that as of this writing, 3 licenses have been distributed. One of them _is_ Active and as far as I can tell it was _not_ done manually through our site.

This may need more looking into, but given that it is using `EDD_License` currently it really shouldn't be working. Maybe that one user modified the API URL temporarily to force it to point to our site?

https://realbigplugins.com/wp-admin/edit.php?post_type=download&page=edd-licenses&s=Project+Panorama+-+Easy+Digital+Downloads&_wpnonce=ed53345e1b&_wp_http_referer=%2Fwp-admin%2Fedit.php%3Fpost_type%3Ddownload%26page%3Dedd-licenses&action=-1&paged=1&action2=-1

**Comment by brashrebel** [comment]
@d4mation thank you for looking into this! Any chance you could help me out first testing and then getting the licensing feature properly implemented? Gosh I thought I tested it before releasing but maybe I didn't. Anyway, I have no time this week and might not next week either.

**Comment by d4mation** [comment]
Yeah, I can help you get that tested and implemented. Might be a bit before I can too I'm afraid. I'd say first order of business would be to test it as-is though in case through some odd miracle it _does_ work.

**Comment by d4mation** [comment]
An activation went through last night, but it has a broken link. Actually, looking at my Issue I opened for EDD Slack, it looks like that was a License Activation for PSP EDD as well. Perhaps the Activation Code in PSP EDD is the true culprit for that bug?

realbigplugins/edd-slack#71

![image](https://user-images.githubusercontent.com/7770631/29212416-7fe1a8ae-7e6c-11e7-9c6d-34a9c3fb2739.png)

https://realbigplugins.com/wp-admin/edit.php?post_type=download&page=edd-licenses&view=overview&license=3217
